version: '2'
services:
  pyspark_notebook:
    image: jupyter/pyspark-notebook
  #  command: start.sh jupyter lab --NotebookApp.token='pyspark'
    volumes:
      - ./work:/home/jovyan/work
    ports:
      - '8888:8888'