version: '3'
services:
  pyspark_notebook:
    build: Dockerfile
    command: start.sh jupyter lab --NotebookApp.token='pyspark'
    volumes:
      - ./work:/home/jovyan/work
    ports:
      - '8888:8888'